### ISSUE TITLE
Download TESS lightcurves

### ISSUE THREAD

**Issue by guynir42** [guynir42/virtualobserver#15]

**Comment by guynir42** [comment]
Here are some things we need to do to get TESS integrated into VO:
1) create a new file named tess.py
2) Use the existing template in ztf.py to make a `ParsObsTESS` and `VirtualTESS` classes. 
3) Make a `fetch_data_from_observatory` function (like the one in `observatory.py` under `VirtualDemoObs` class. It should accept the arguments `self, cat_row, verbose=0` and any others that may be needed. This should return a dataframe with all photometry for a source, assuming `cat_row` is a dictionary that has `ra` and `dec` keys
4) Add a `reduce_to_lightcurves` function similar to that in `VirtualZTF`. This function should accept `self, datasets, source=None, init_kwargs={}` and any other arguments (probably want to add `_**` in the end to absorb additional but irrelevant keywords). This function should split up a dataset of raw data into lightcurves for different visits.

**Comment by felixzhu555** [comment]
Should we use SAP_FLUX or PDCSAP_FLUX? The TESS documentation says SAP is "Simple aperture photometry light curve" and PDCSAP is "PDC corrected SAP light curve". I'm going to default to PDC.

**Comment by guynir42** [comment]
Sounds like a good bet to use the corrected lightcurve. I'll try to figure out what the differences are. It could also be good to download a few examples and plot them to try to see the differences.

**Comment by felixzhu555** [comment]
Plotted one sample, it seems like PDC values are higher than SAP values by about 1000 e-/s (15400 vs 14400 average). 
Also, is this paper related to our goals? https://www.researchgate.net/publication/358457993_Searching_for_white_dwarf_variables_in_TESS_data

**Comment by felixzhu555** [comment]
Comparing by magnitude seems a bit fuzzy, querying by MAST returns observations with slightly different mag values than those for the GAIA catalog. For example, GAIA's g_mean_mag = 8.524133, but astroquery yields GAIAmag = 8.47446. I wanted to clarify, what exactly is mag being used for in fetch_data? Is it just used to filter out anything with mag > threshold?

**Comment by felixzhu555** [comment]
astroquery also seems to have HTTP timeouts quite frequently, don't know how we can have the code handle such random issues.
